// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALe5bgE0ekKijpob0xofLlIQFpJ11COA8',
    appId: '1:1017626603329:web:58d7c4f0ea406b6fac3bc0',
    messagingSenderId: '1017626603329',
    projectId: 'enciclomovie',
    authDomain: 'enciclomovie.firebaseapp.com',
    storageBucket: 'enciclomovie.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEOcx6i6b81Ss0x1Emrif41Us1bKaPC3c',
    appId: '1:1017626603329:android:1cdb463807680677ac3bc0',
    messagingSenderId: '1017626603329',
    projectId: 'enciclomovie',
    storageBucket: 'enciclomovie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB-FgDqCp98Z_x-c_DdZfY9lKE4b53dao',
    appId: '1:1017626603329:ios:99ca688130c30415ac3bc0',
    messagingSenderId: '1017626603329',
    projectId: 'enciclomovie',
    storageBucket: 'enciclomovie.firebasestorage.app',
    iosBundleId: 'com.example.enciclomovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB-FgDqCp98Z_x-c_DdZfY9lKE4b53dao',
    appId: '1:1017626603329:ios:99ca688130c30415ac3bc0',
    messagingSenderId: '1017626603329',
    projectId: 'enciclomovie',
    storageBucket: 'enciclomovie.firebasestorage.app',
    iosBundleId: 'com.example.enciclomovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALe5bgE0ekKijpob0xofLlIQFpJ11COA8',
    appId: '1:1017626603329:web:1e41b3a64f92d026ac3bc0',
    messagingSenderId: '1017626603329',
    projectId: 'enciclomovie',
    authDomain: 'enciclomovie.firebaseapp.com',
    storageBucket: 'enciclomovie.firebasestorage.app',
  );

}